import './globals.css';
import StyledComponentsRegistry from '../lib/registry';

import Nav from '@/layout/Nav';

export const metadata = {
  title: '나의 넥스트앱',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <StyledComponentsRegistry>
          <Nav />
          <>{children}</>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
