import 'nes.css/css/nes.min.css';
import './globals.css';
import StyledComponentsRegistry from '../lib/registry';

import tw from 'tailwind-styled-components';

import Header from '@/layout/Header';
import Footer from '@/layout/Footer';

import Providers from '@/lib/provider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

export const metadata = {
  title: '나의 넥스트앱',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <StyledComponentsRegistry>
          <Providers>
            <ReactQueryDevtools initialIsOpen={true} />
            <Header />
            <Container>
              <Content>{children}</Content>
            </Container>
            <Footer />
          </Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}

const Container = tw.div`
max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 min-h-screen
`;

const Content = tw.div`
px-3
py-3
`;
